### ISSUE TITLE
Reverse GEO Coding module

### ISSUE THREAD

**Issue by pugoboss** [hqdaemon/geo#1]
In accordance with https://surfy.one/geo/reverse GEO has a Reverse Geocoding module.
Geo.reverse is undefined for JS now, is it not implemented yet?

**Comment by theastroscout** [comment]
Yes, you're right. I'll add it later today!

**Comment by hqdaemon** [comment]
#https://github.com/hqdaemon/geo/tree/1-reverse-geo-coding-module

**Comment by theastroscout** [comment]
All set!

Usage:
```javascript
let coords = [51.505563,-0.023309];
await geo.reverse(coords);
```
